### ISSUE TITLE
Problem with CN/ACI/STO-3G

### ISSUE THREAD

**Issue by berquist** [shivupa/pyci#5]
```
Q space size:  7
Traceback (most recent call last):
  File "examples/cn_sto3g.py", line 117, in <module>
    aci(mol, sigma=100, gamma=0.0001, convergence=1e-10, printroots=4, iter_min=0, visualize=False)
  File "/home/eric/development/pyci/methods/utils.py", line 883, in aci
    eig_vals, eig_vecs = sp.sparse.linalg.eigsh(targetham, k=2*printroots)
  File "/usr/lib/python3.5/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1522, in eigsh
    raise ValueError("k must be between 1 and the order of the "
ValueError: k must be between 1 and the order of the square input matrix.
```

**Comment by shivupa** [comment]
I believe this is fixed by changing, k=2*printroots to k=printroots. I do not see any reason to compute more roots than what we need considering we throw the others away anyways. I have changed this and pushed. I will not close this yet as I have not actually converged the test.
